2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,369 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,650 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,650 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,666 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:35,666 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,088 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,088 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,088 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,104 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,104 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,104 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,104 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,104 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,119 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:07:36,119 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:31,265 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:31,630 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:31,927 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:32,224 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:32,568 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:32,865 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:33,146 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:33,474 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:33,793 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-15 23:11:34,117 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:33,313 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:33,661 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:33,949 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:34,237 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:34,501 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:34,792 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:34,795 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:35,066 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:35,376 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:35,672 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:36,290 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:36,626 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:36,970 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:37,258 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:37,574 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:37,861 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:37,863 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:38,163 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:38,885 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:39,212 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:39,493 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:39,817 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:40,132 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:40,441 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:40,716 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:41,017 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:41,313 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:42,129 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:42,419 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:42,688 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:42,997 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:43,001 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:43,287 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:43,604 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:44,101 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:45,214 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:45,536 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:45,837 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:45,838 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:45,840 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:46,142 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:46,422 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:46,750 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:47,059 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:47,398 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:55,095 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:55,402 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:55,717 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,027 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,338 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,340 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,649 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,937 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:56,939 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 17:08:57,255 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:26,069 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:26,407 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:26,710 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:26,713 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 731, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:27,001 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:27,286 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:27,288 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:27,597 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:28,111 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:00:28,445 - ERROR - weibo-news-spider.py[:752] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 332, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 644, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:19,723 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:19,728 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,048 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,356 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,358 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 735, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,648 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,943 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:20,946 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:21,314 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:21,639 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('//string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:38,431 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:38,434 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:38,744 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:39,292 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:39,294 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 735, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:39,598 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:39,884 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:39,887 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:40,251 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:18:40,606 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 648, in parse_weibo
    weibo['text'] = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:55,636 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,003 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,006 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,296 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,651 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,655 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 735, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:56,937 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:57,219 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:57,222 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 751, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:33:57,507 - ERROR - weibo-news-spider.py[:756] - 'str' object has no attribute 'xpath'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 747, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 336, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 651, in parse_weibo
    weibo['article_url'] = self.get_article_url(selector)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 559, in get_article_url
    text = selector.xpath('string(.)')
AttributeError: 'str' object has no attribute 'xpath'
2021-11-16 19:50:24,807 - ERROR - weibo-news-spider.py[:530] - 'Weibo' object has no attribute 'get_video_url'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 525, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 436, in parse_weibo
    weibo['video_url'] = self.get_video_url(weibo_info)
AttributeError: 'Weibo' object has no attribute 'get_video_url'
2021-11-16 19:50:25,119 - ERROR - weibo-news-spider.py[:530] - 'Weibo' object has no attribute 'get_video_url'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 521, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 301, in get_long_weibo
    weibo = self.parse_weibo(weibo_info)
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 436, in parse_weibo
    weibo['video_url'] = self.get_video_url(weibo_info)
AttributeError: 'Weibo' object has no attribute 'get_video_url'
2021-11-16 20:12:40,754 - ERROR - weibo-news-spider.py[:1031] - 
Traceback (most recent call last):
  File "d:\sycode\sltg\src\main\spider\weibo-news-spider.py", line 1031, in get_pages
    self.get_user_info()
  File "d:\sycode\sltg\src\main\spider\weibo-news-spider.py", line 251, in get_user_info
    js = self.get_json(params)
  File "d:\sycode\sltg\src\main\spider\weibo-news-spider.py", line 251, in get_user_info
    js = self.get_json(params)
  File "D:\Program Files\anaconda\envs\paperTest\lib\bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "D:\Program Files\anaconda\envs\paperTest\lib\bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
2021-11-16 20:18:18,497 - ERROR - weibo-news-spider.py[:1064] - 'Weibo' object has no attribute 'original_pic_download'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1061, in get_pages
    self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1018, in write_data
    if self.original_pic_download:
AttributeError: 'Weibo' object has no attribute 'original_pic_download'
2021-11-16 20:18:45,087 - ERROR - weibo-news-spider.py[:1064] - 'Weibo' object has no attribute 'original_pic_download'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1061, in get_pages
    self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1018, in write_data
    if self.original_pic_download:
AttributeError: 'Weibo' object has no attribute 'original_pic_download'
2021-11-16 20:19:04,439 - ERROR - weibo-news-spider.py[:1064] - 'Weibo' object has no attribute 'original_pic_download'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1061, in get_pages
    self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1018, in write_data
    if self.original_pic_download:
AttributeError: 'Weibo' object has no attribute 'original_pic_download'
2021-11-16 20:19:38,644 - ERROR - weibo-news-spider.py[:1064] - 'Weibo' object has no attribute 'original_pic_download'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1061, in get_pages
    self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 1018, in write_data
    if self.original_pic_download:
AttributeError: 'Weibo' object has no attribute 'original_pic_download'
2021-11-16 22:18:44,458 - ERROR - weibo-news-spider.py[:1029] - 'Weibo' object has no attribute 'user_to_database'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 996, in get_pages
    self.get_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 277, in get_user_info
    self.user_to_database()
AttributeError: 'Weibo' object has no attribute 'user_to_database'
2021-11-16 22:18:44,913 - ERROR - weibo-news-spider.py[:1029] - 'Weibo' object has no attribute 'user_to_database'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 996, in get_pages
    self.get_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 277, in get_user_info
    self.user_to_database()
AttributeError: 'Weibo' object has no attribute 'user_to_database'
2021-11-16 22:18:45,266 - ERROR - weibo-news-spider.py[:1029] - 'Weibo' object has no attribute 'user_to_database'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 996, in get_pages
    self.get_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 277, in get_user_info
    self.user_to_database()
AttributeError: 'Weibo' object has no attribute 'user_to_database'
2021-11-16 22:18:45,617 - ERROR - weibo-news-spider.py[:1029] - 'Weibo' object has no attribute 'user_to_database'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 996, in get_pages
    self.get_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 277, in get_user_info
    self.user_to_database()
AttributeError: 'Weibo' object has no attribute 'user_to_database'
2021-11-27 12:39:00,008 - WARNING - weibo-news-spider.py[:832] - 系统中可能没有安装pymysql库，请先运行 pip install pymysql ，再运行程序
2021-11-27 12:41:31,639 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:42:59,375 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:44:01,664 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:44:02,086 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:44:45,566 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:44:46,109 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:45:20,420 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:45:20,879 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:46:06,750 - ERROR - weibo-news-spider.py[:881] - (1146, "Table 'newsdata.newsdata' doesn't exist")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'newsdata.newsdata' doesn't exist")
2021-11-27 12:48:17,907 - ERROR - weibo-news-spider.py[:881] - (1054, "Unknown column 'gender' in 'field list'")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 876, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'gender' in 'field list'")
2021-11-27 12:48:47,370 - ERROR - weibo-news-spider.py[:880] - (1054, "Unknown column 'statuses_count' in 'field list'")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 875, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'statuses_count' in 'field list'")
2021-11-27 12:49:56,361 - ERROR - weibo-news-spider.py[:1002] - 'statuses_count'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 970, in get_pages
    self.print_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 404, in print_user_info
    logger.info(u'微博数：%d', self.user['statuses_count'])
KeyError: 'statuses_count'
2021-11-27 12:49:56,812 - ERROR - weibo-news-spider.py[:1002] - 'statuses_count'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 970, in get_pages
    self.print_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 404, in print_user_info
    logger.info(u'微博数：%d', self.user['statuses_count'])
KeyError: 'statuses_count'
2021-11-27 12:49:57,440 - ERROR - weibo-news-spider.py[:1002] - 'statuses_count'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 970, in get_pages
    self.print_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 404, in print_user_info
    logger.info(u'微博数：%d', self.user['statuses_count'])
KeyError: 'statuses_count'
2021-11-27 12:49:57,969 - ERROR - weibo-news-spider.py[:1002] - 'statuses_count'
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 970, in get_pages
    self.print_user_info()
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 404, in print_user_info
    logger.info(u'微博数：%d', self.user['statuses_count'])
KeyError: 'statuses_count'
2021-11-27 12:52:05,003 - ERROR - weibo-news-spider.py[:883] - (1054, "Unknown column 'statuses_count' in 'field list'")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 878, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'statuses_count' in 'field list'")
2021-11-27 12:52:12,845 - ERROR - weibo-news-spider.py[:883] - (1054, "Unknown column 'statuses_count' in 'field list'")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 878, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'statuses_count' in 'field list'")
2021-11-27 12:54:17,391 - ERROR - weibo-news-spider.py[:883] - (1054, "Unknown column 'statuses_count' in 'field list'")
Traceback (most recent call last):
  File "D:\sycode\SLTG\src\main\spider\weibo-news-spider.py", line 878, in mysql_insert
    cursor.executemany(
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 182, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\Program Files\anaconda\envs\paperTest\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'statuses_count' in 'field list'")
